In [542]:
from tensorflow.keras.layers import *
from tensorflow.keras.activations import *
from tensorflow.keras.optimizers import *
from tensorflow.keras.losses import *
from tensorflow.keras.metrics import *
from tensorflow.keras.initializers import *
from tensorflow.keras.utils import *
from tensorflow.keras.models import *
from tensorflow.keras.datasets import *
import tensorflow.keras as keras
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import datetime
import os
import pandas as pd
from PIL import Image
from matplotlib import image
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [543]:
main_path="C:\\Users\\Amrta\\Documents\\GitHub\\projetannuel4IABD2\\ETAPE_3\\Scripts_Recup_Data\\"
open_folder = os.listdir(main_path)
Data_base_learning = main_path+open_folder[2]
Points_equipe = main_path+open_folder[3]
Teams_puissance = main_path+open_folder[5]

In [544]:
train_csv = pd.read_csv(Data_base_learning,sep=";",encoding="utf-8")
train_csv.score.unique()

array([2, 1, 0], dtype=int64)

In [545]:
dataset = train_csv.values

In [546]:
df_train,df_test=train_test_split(dataset, random_state=0, test_size=0.2)
print(len(df_train), len(df_test))

1032 259


In [547]:
df_train

array([[ 906,    2, 6273, 3267],
       [ 582,    1, 2956, 6821],
       [ 487,    2, 2817, 8832],
       ...,
       [1644,    1, 9329, 8083],
       [ 661,    1, 7938, 2705],
       [ 877,    2,  100, 3861]], dtype=int64)

In [548]:
def define_labels(df):
    
    dataset = df
    X = dataset[:,2:4]
    Y = dataset[:,1]
        
    return np.array(X),np.array(Y)

# for i in df_train:
#     print(i[1])

#         tmp.append(df.iloc[i]["healthy"])
#         tmp.append(df.iloc[i]["multiple_diseases"])
#         tmp.append(df.iloc[i]["rust"])
#         tmp.append(df.iloc[i]["scab"])
#         one_hot.append(tmp)
        
#     return np.array(images),np.array(one_hot)

In [549]:
x_train,y_train = define_labels(df_train)
print(x_train.shape,y_train.shape)
x_test,y_test = define_labels(df_test)

(1032, 2) (1032,)


In [550]:
print(np.unique(y_train))
y_train = y_train.astype(np.int)

[0 1 2]


In [551]:
for row in y_train:
     print(row)

2
1
2
1
2
0
1
1
1
0
1
2
2
1
2
1
1
2
1
2
1
0
1
0
1
2
2
0
2
0
0
1
1
1
1
1
0
2
2
1
0
1
2
0
1
1
1
2
1
1
0
0
1
0
0
2
0
0
0
1
1
0
1
2
2
2
1
0
1
0
1
2
2
2
2
0
1
0
1
0
1
2
1
1
2
1
1
0
1
2
1
2
2
2
1
2
1
0
0
2
0
2
2
2
2
2
2
0
1
2
1
1
1
1
1
1
2
1
1
2
1
2
0
0
2
1
1
0
1
0
0
2
1
2
1
2
0
1
1
1
1
2
2
1
1
0
1
1
2
0
1
1
0
1
1
1
0
1
1
1
1
0
0
2
1
0
2
2
1
2
2
1
1
1
1
1
1
1
0
0
2
1
2
2
1
1
2
2
0
2
1
1
2
1
0
2
1
0
2
2
2
1
1
1
1
1
1
2
2
0
2
2
0
0
1
1
1
0
0
2
1
0
2
1
1
0
2
2
2
1
1
1
2
2
1
0
1
0
1
2
1
1
2
1
1
1
0
2
2
1
1
2
2
0
0
1
0
0
2
2
0
1
0
2
1
1
2
0
1
2
0
2
2
2
2
1
2
1
1
1
2
0
0
1
0
1
1
1
1
2
1
2
0
2
2
1
0
1
1
1
2
2
1
1
0
0
1
0
1
1
1
1
1
2
2
0
2
1
1
1
0
1
0
1
1
0
1
1
1
1
2
2
2
1
0
1
0
2
1
1
1
2
1
1
1
2
1
1
2
0
0
2
2
1
1
1
1
1
2
2
1
1
1
1
2
1
1
1
0
0
1
1
0
2
2
1
1
1
1
1
2
0
0
0
0
2
1
0
1
0
2
0
2
2
1
1
1
2
1
1
1
2
0
1
0
1
1
1
2
0
1
1
0
1
1
2
0
2
1
2
0
2
1
1
1
0
1
1
1
1
2
1
2
1
2
2
0
0
0
2
2
1
1
2
2
0
2
2
1
1
1
1
0
2
0
1
0
1
0
2
1
1
1
0
1
1
1
1
2
2
0
1
2
0
2
1
1
2
1
1
0
2
1
1
0
1
1
1
0
0
2
1
1
0
0
1
0
1
1
0


In [561]:
def create_model():
    
    model = Sequential()
    model.add(Dense(3, input_dim=x_train.shape[1], activation='relu'))
    model.add(Dense(3, input_dim=x_train.shape[1], activation='linear'))
    model.add(Dense(3, input_dim=x_train.shape[1], activation='linear'))
    model.add(Dense(3, activation='softmax'))
    model.compile(loss="sparse_categorical_crossentropy",
                  optimizer=Adam(),
                  metrics=["accuracy"])
    return model

In [562]:
model = create_model()
print(model.summary())

Model: "sequential_49"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_103 (Dense)            (None, 3)                 9         
_________________________________________________________________
dense_104 (Dense)            (None, 3)                 12        
_________________________________________________________________
dense_105 (Dense)            (None, 3)                 12        
_________________________________________________________________
dense_106 (Dense)            (None, 3)                 12        
Total params: 45
Trainable params: 45
Non-trainable params: 0
_________________________________________________________________
None


In [563]:
model.fit(x_train, y_train,validation_data=(x_test, y_test),epochs=10)

Train on 1032 samples, validate on 259 samples
Epoch 1/10
1032/1032 [==============================] - 1s 486us/sample - loss: 2634.3793 - accuracy: 0.2510 - val_loss: 2023.0840 - val_accuracy: 0.2510
Epoch 2/10
1032/1032 [==============================] - 0s 61us/sample - loss: 1469.1791 - accuracy: 0.2868 - val_loss: 1182.5934 - val_accuracy: 0.2973
Epoch 3/10
1032/1032 [==============================] - 0s 74us/sample - loss: 913.9087 - accuracy: 0.3207 - val_loss: 766.0837 - val_accuracy: 0.3089
Epoch 4/10
1032/1032 [==============================] - 0s 47us/sample - loss: 574.1968 - accuracy: 0.3295 - val_loss: 434.8113 - val_accuracy: 0.3166
Epoch 5/10
1032/1032 [==============================] - 0s 47us/sample - loss: 317.9813 - accuracy: 0.3740 - val_loss: 271.1169 - val_accuracy: 0.4595
Epoch 6/10
1032/1032 [==============================] - 0s 51us/sample - loss: 247.9775 - accuracy: 0.4041 - val_loss: 227.2489 - val_accuracy: 0.4556
Epoch 7/10
1032/1032 [====================

In [566]:
predictions = model.predict((x_test, y_test))

In [572]:
print(x_test[25])
print(y_test[25])
plt.show()
np.argmax(predictions[25])

[3029 2045]
1


1