In [46]:
from tensorflow.keras.layers import *
from tensorflow.keras.activations import *
from tensorflow.keras.optimizers import *
from tensorflow.keras.losses import *
from tensorflow.keras.metrics import *
from tensorflow.keras.initializers import *
from tensorflow.keras.utils import *
from tensorflow.keras.models import *
from tensorflow.keras.datasets import *
import tensorflow.keras as keras
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import datetime
import os
import pandas as pd
from PIL import Image
from matplotlib import image
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.callbacks import EarlyStopping , ModelCheckpoint,ReduceLROnPlateau

In [62]:
main_path="C:\\Users\\Amrta\\Documents\\GitHub\\projetannuel4IABD2\\ETAPE_3\\Scripts_Recup_Data\\"
open_folder = os.listdir(main_path)
Data_base_learning = main_path+open_folder[3]
Data_base_learning_v2 = main_path+open_folder[4]
path2 = "C:\\Users\\Amrta\\Documents\\GitHub\\projetannuel4IABD2\\ETAPE_3\\Scripts_Recup_Data\\Projet_Annuel_Data\\"
open_folder1= os.listdir(path2)
Data_train = path2+open_folder1[10]
Data_test = path2+open_folder1[9]
print(open_folder1)
print(Data_test)

['.DS_Store', '.ipynb_checkpoints', '2014', '2015', '2016', '2017', '2018', 'All_years', 'Data_API.ipynb', 'Data_Test_Foot.csv', 'Data_Train_Foot.csv', 'Points_Equipe_Hist', 'Points_Equipe_Hist_VF', 'Recup_Data_Historical.ipynb', 'Teams_puiss.csv', 'Web_Score.ipynb']
C:\Users\Amrta\Documents\GitHub\projetannuel4IABD2\ETAPE_3\Scripts_Recup_Data\Projet_Annuel_Data\Data_Test_Foot.csv


In [48]:
train_csv = pd.read_csv(Data_train,sep=";",encoding="utf-8")
display(train_csv)

Unnamed: 0                 date                homeTeam  \
0               0  2019-08-09 00:00:00            AS Monaco FC   
1               1  2019-08-10 00:00:00  Olympique de Marseille   
2               2  2019-08-10 00:00:00         Montpellier HSC   
3               3  2019-08-10 00:00:00                OGC Nice   
4               4  2019-08-10 00:00:00       Stade Brestois 29   
...           ...                  ...                     ...   
11514         375           2018-05-19              Villarreal   
11515         376           2018-05-20              Ath Bilbao   
11516         377           2018-05-20              Ath Madrid   
11517         378           2018-05-20               Barcelona   
11518         379           2018-05-20                Valencia   

                    awayTeam  score  goalHomeTeam_FullTime  \
0         Olympique Lyonnais    2.0                    0.0   
1             Stade de Reims    2.0                    0.0   
2      Stade Rennais FC 1901    2.0                    0.0   
3                  Amiens SC    1.0                    2.0   
4                Toulouse FC    0.0                    1.0   
...                      ...    ...                    ...   
11514            Real Madrid    0.0                    2.0   
11515                Espanol    2.0                    0.0   
11516                  Eibar    0.0                    2.0   
11517               Sociedad    1.0                    1.0   
11518              La Coruna    1.0                    2.0   

       goalAwayTeam_FullTime  goalHomeTeam_HalfTime  goalAwayTeam_HalfTime  \
0                        3.0                    0.0                    2.0   
1                        2.0                    0.0                    0.0   
2                        1.0                    0.0                    1.0   
3                        1.0                    1.0                    0.0   
4                        1.0                    1.0                    0.0   
...                      ...                    ...                    ...   
11514                    2.0                    0.0                    2.0   
11515                    1.0                    0.0                    1.0   
11516                    2.0                    1.0                    1.0   
11517                    0.0                    0.0                    0.0   
11518                    1.0                    1.0                    0.0   

       NbgoalsHalfTime  ...  moy_goals_home  moy_goals_away  \
0                  2.0  ...        0.000000        0.000000   
1                  0.0  ...        0.000000        0.000000   
2                  1.0  ...        0.000000        0.000000   
3                  1.0  ...        0.000000        0.000000   
4                  1.0  ...        0.000000        0.000000   
...                ...  ...             ...             ...   
11514              2.0  ...        1.370370        2.814815   
11515              1.0  ...        1.306878        1.164021   
11516              2.0  ...        1.724868        1.253968   
11517              0.0  ...        2.920635        1.444444   
11518              1.0  ...        1.539683        1.074074   

       moy_goals_half_home  moy_goals_half_away  moy_goals_conceded_home  \
0                 0.000000             0.000000                 0.000000   
1                 0.000000             0.000000                 0.000000   
2                 0.000000             0.000000                 0.000000   
3                 0.000000             0.000000                 0.000000   
4                 0.000000             0.000000                 0.000000   
...                    ...                  ...                      ...   
11514             0.613757             1.439153                 0.984127   
11515             0.587302             0.497354                 1.164021   
11516             0.693122             0.608466                 0.640212   
11517          

In [49]:
train_columns={'win_cons_home':train_csv.win_cons_home,'win_cons_away':train_csv.win_cons_away,'lose_cons_home':train_csv.lose_cons_home,'lose_cons_away':train_csv.lose_cons_away,'puissance_HomeTeam':train_csv.puissance_HomeTeam,'puissance_AwayTeam':train_csv.puissance_AwayTeam}
df = pd.DataFrame(train_columns)
X = df.values
X

array([[    0,     0,     0,     0,  2409,  6154],
       [    0,     0,     0,     0,  4008,  3054],
       [    0,     0,     0,     0,  3029,  4815],
       ...,
       [    1,     2,     0,     0, 13709,  4725],
       [    0,     1,     1,     0, 14840,  4571],
       [    1,     0,     0,     1,  8716,   100]], dtype=int64)

In [64]:
y_train_columns={'goalHomeTeam_HalfTime':train_csv.goalHomeTeam_HalfTime,'goalAwayTeam_HalfTime':train_csv.goalAwayTeam_HalfTime}
df1 = pd.DataFrame(y_train_columns)
Y= df1.values
Y
# Y = train_csv['win_cons_home':train_csv.win_cons_home].values
# Y[0]
# Y = train_csv['score'].values
# X[0]


array([[0., 2.],
       [0., 0.],
       [0., 1.],
       ...,
       [1., 1.],
       [0., 0.],
       [1., 0.]])

In [65]:
x_train, x_validation, y_train, y_validation =train_test_split(X,Y, test_size=0.2)
print(x_train.shape,y_train.shape)
y_train = y_train.astype(int)
y_validation = y_validation.astype(int)

(9215, 6) (9215, 2)


In [66]:
x_train

array([[    2,     2,     0,     0,  5086,  4420],
       [    0,     0,     1,     1,   100,  5220],
       [    0,     2,     0,     0,  4476,  7680],
       ...,
       [    0,     1,     0,     0,   100,   100],
       [    0,     3,     1,     0,  2008,  9380],
       [    0,     1,     0,     0, 13105,  4803]], dtype=int64)

In [67]:
def create_model():
    
#     model = Sequential()
#     model.add(Dense(6, input_dim=x_train.shape[1], activation='relu'))
#     model.add(Dense(6, activation='softmax'))
#     model.compile(loss="sparse_categorical_crossentropy",
#                   optimizer=Adam(),
#                   metrics=["accuracy"])
    
    model = Sequential()
    model.add(Dense(2, input_dim=6, activation="relu"))
    model.add(Dense(2,activation = "softmax"))
    model.compile(loss="mse", optimizer="adam")
    return model

In [68]:
model = create_model()
print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_4 (Dense)              (None, 2)                 14        
_________________________________________________________________
dense_5 (Dense)              (None, 2)                 6         
Total params: 20
Trainable params: 20
Non-trainable params: 0
_________________________________________________________________
None


In [69]:
save = ModelCheckpoint('model_score_exact_mi_temps.h5', monitor = 'val_accuracy' , verbose = 1 , save_best_only = True)

In [70]:
history = model.fit(x_train, y_train,validation_data=(x_validation,y_validation),batch_size=90,epochs=100,callbacks = [save])

Train on 9215 samples, validate on 2304 samples
Epoch 1/100
9215/9215 [==============================] - 1s 115us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 2/100
9215/9215 [==============================] - 0s 35us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 3/100
9215/9215 [==============================] - 0s 39us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 4/100
9215/9215 [==============================] - 0s 33us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 5/100
9215/9215 [==============================] - 0s 33us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 6/100
9215/9215 [==============================] - 0s 46us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 7/100
9215/9215 [==============================] - 0s 29us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 8/100
9215/9215 [==============================] - 0s 29us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 9/100
9215/9215 [==============================] - 0s 31us/sample - loss: 0.7806 - val_loss: 0.81

Epoch 33/100
9215/9215 [==============================] - 0s 33us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 34/100
9215/9215 [==============================] - 0s 35us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 35/100
9215/9215 [==============================] - 0s 32us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 36/100
9215/9215 [==============================] - 0s 32us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 37/100
9215/9215 [==============================] - 0s 28us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 38/100
9215/9215 [==============================] - 0s 36us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 39/100
9215/9215 [==============================] - 0s 32us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 40/100
9215/9215 [==============================] - 0s 34us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 41/100
9215/9215 [==============================] - 0s 37us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 42/100
9215/9215 [=============

Epoch 65/100
9215/9215 [==============================] - 0s 31us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 66/100
9215/9215 [==============================] - 0s 35us/sample - loss: 0.7825 - val_loss: 0.8149
Epoch 67/100
9215/9215 [==============================] - 0s 34us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 68/100
9215/9215 [==============================] - 0s 41us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 69/100
9215/9215 [==============================] - 0s 32us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 70/100
9215/9215 [==============================] - 0s 33us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 71/100
9215/9215 [==============================] - 0s 34us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 72/100
9215/9215 [==============================] - 0s 35us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 73/100
9215/9215 [==============================] - 0s 33us/sample - loss: 0.7806 - val_loss: 0.8149
Epoch 74/100
9215/9215 [=============

Epoch 97/100
9215/9215 [==============================] - 0s 35us/sample - loss: 0.7583 - val_loss: 0.7908
Epoch 98/100
9215/9215 [==============================] - 0s 41us/sample - loss: 0.7580 - val_loss: 0.7916
Epoch 99/100
9215/9215 [==============================] - 0s 32us/sample - loss: 0.7576 - val_loss: 0.7904
Epoch 100/100
9215/9215 [==============================] - 0s 37us/sample - loss: 0.7574 - val_loss: 0.7906


In [72]:
test_csv = pd.read_csv(Data_test,sep=";",encoding="utf-8")
display(test_csv)

Unnamed: 0        date     status                homeTeam  \
0          1417  2020-06-28   FINISHED            UC Sampdoria   
1          1416  2020-06-28   FINISHED          Udinese Calcio   
2          1415  2020-06-28   FINISHED              SSC Napoli   
3           691  2020-06-28   FINISHED              Watford FC   
4          1414  2020-06-28   FINISHED                AC Milan   
..          ...         ...        ...                     ...   
290        2024  2020-07-26  SCHEDULED  Sport Lisboa e Benfica   
291        2025  2020-07-26  SCHEDULED              Vitória FC   
292        2026  2020-07-26  SCHEDULED          CD Santa Clara   
293        2027  2020-07-26  SCHEDULED         Portimonense SC   
294        2028  2020-07-26  SCHEDULED             Boavista FC   

                       awayTeam  win_cons_home  win_cons_away  lose_cons_home  \
0               Bologna FC 1909              0              0               2   
1                   Atalanta BC              0              7               1   
2                     SPAL 2013              2              0               0   
3                Southampton FC              0              0               1   
4                       AS Roma              1              3               0   
..                          ...            ...            ...             ...   
290  Sporting Clube de Portugal              1              0               0   
291       Os Belenenses Futebol              0              0               4   
292                  Vitória SC              0              2               2   
293                     CD Aves              0              0               1   
294                  Rio Ave FC              0              0               1   

     lose_cons_away  moy_goals_home  moy_goals_away  moy_goals_half_home  \
0                 2        1.111111        1.407407             0.259259   
1                 0        0.777778        2.657143             0.407407   
2                 1        1.617647        0.740741             0.705882   
3                 1        0.903226        1.225806             0.419355   
4                 0        1.185185        1.962963             0.444444   
..              ...             ...             ...                  ...   
290               0        2.000000        1.566667             0.694444   
291               1        0.800000        0.833333             0.333333   
292               0        0.966667        1.633333             0.400000   
293               3        0.800000        0.766667             0.400000   
294               1        0.833333        1.400000             0.466667   

     moy_goals_half_away  moy_goals_conceded_home  moy_goals_conceded_away  \
0               0.555556                 1.777778                 1.629630   
1               1.142857                 1.085714                 1.514286   
2               0.333333                 1.518519                 1.666667   
3               0.548387                 1.483871                 1.741935   
4               0.888889                 1.296296                 1.333333   
..                   ...                      ...                      ...   
290             0.866667                 1.166667                 1.000000   
291             0.566667                 1.333333                 1.666667   
292             0.666667                 1.200000                 1.066667   
293             0.466667                 1.333333                 1.966667   
294             0.733333                 1.066667                 1.100000   

     moy_goals_conceded_half_home  moy_goals_conceded_half_away  \
0                        0.962963                      0.925926   
1                        0.485714                      0.742857   
2                        0.666667                      0.740741   
3                        0.612903                      0.741935   
4                        0.407407                     

In [60]:
ypred = model.predict(x_test)
print("y1 MSE:%.4f" % mean_squared_error(y_test[:,0], ypred[:,0])) 
print("y2 MSE:%.4f" % mean_squared_error(y_test[:,1], ypred[:,1]))

y1 MSE:1.9246
y2 MSE:2.3340


In [61]:
x_ax = range(len(x_test))
plt.scatter(x_ax, y_test[:,0],  s=6, label="y1-test")
plt.plot(x_ax, ypred[:,0], label="y1-pred")
plt.scatter(x_ax, y_test[:,1],  s=6, label="y2-test")
plt.plot(x_ax, ypred[:,1], label="y2-pred")
plt.legend()
plt.show()

NameError: name 'x_test' is not defined

In [153]:
predictions = model.predict((x_test, y_test))

In [170]:
print(x_test[255])
print(y_test[255])
plt.show()
preds = model.predict((x_test, y_test))
print(preds[255])
# np.argmax(predictions[98])

[   0    0    1    2 4146 7311]
[0 0]
[1. 0.]


## Prédiction Unique mi-temps

In [155]:
puissance_homeTeam = 0
puissance_awayTeam = 4523998
win_cons_home = -1
win_cons_away = -1
lose_cons_home = -1
lose_cons_away= -1
predictions1 = model.predict(np.array([[win_cons_home,win_cons_away,lose_cons_home,lose_cons_away,puissance_homeTeam,puissance_awayTeam]])) # predictions avec puissance de teams au hasard
predictions1

array([[1., 0.]], dtype=float32)

In [156]:
unique = train_csv.values
goalHHalf_time = []
for i in unique:
    puissance_homeTeam = i[15]
    puissance_awayTeam = i[16]
    win_cons_home = i[11]
    win_cons_away = i[12]
    lose_cons_home = i[13]
    lose_cons_away= i[14]
    predictions1 = model.predict(np.array([[win_cons_home,win_cons_away,lose_cons_home,lose_cons_away,puissance_homeTeam,puissance_awayTeam]])) # predictions avec puissance de teams au hasard
    goal = predictions1
    goalHHalf_time.append(goal)
    print(goal,puissance_homeTeam,puissance_awayTeam)


[[1. 0.]] 2409 6154
[[1. 0.]] 4008 3054
[[1. 0.]] 3029 100
[[1. 0.]] 2803 2045
[[1. 0.]] 2156 1065
[[1. 0.]] 2690 2298
[[1. 0.]] 100 3749
[[1. 0.]] 4207 3029
[[1. 0.]] 3627 1736
[[1. 0.]] 9495 2020
[[1. 0.]] 6154 2690
[[1. 0.]] 3029 4008
[[1. 0.]] 2298 3029
[[1. 0.]] 1065 100
[[1. 0.]] 2020 2803
[[1. 0.]] 1736 2409
[[1. 0.]] 2045 4207
[[1. 0.]] 3749 2156
[[1. 0.]] 3054 3627
[[1. 0.]] 100 9495
[[1. 0.]] 2156 3054
[[1. 0.]] 2690 1736
[[1. 0.]] 100 2298
[[1. 0.]] 2045 3029
[[1. 0.]] 2409 2020
[[1. 0.]] 3627 100
[[1. 0.]] 9495 1065
[[1. 0.]] 3029 6154
[[1. 0.]] 4207 3749
[[1. 0.]] 2803 4008
[[1. 0.]] 1736 9495
[[1. 0.]] 6154 2298
[[1. 0.]] 1065 2045
[[1. 0.]] 2690 100
[[1. 0.]] 3029 3029
[[1. 0.]] 2020 2156
[[1. 0.]] 100 2803
[[1. 0.]] 3054 4207
[[1. 0.]] 3627 2409
[[1. 0.]] 4008 3749
[[1. 0.]] 4207 2690
[[1. 0.]] 2045 6154
[[1. 0.]] 9495 3627
[[1. 0.]] 3029 2803
[[1. 0.]] 2298 1736
[[1. 0.]] 2156 100
[[1. 0.]] 100 2020
[[1. 0.]] 3029 3054
[[1. 0.]] 3749 1065
[[1. 0.]] 2409 4008
[[1. 0.]] 

[[1. 0.]] 5188 3982
[[1. 0.]] 4146 2482
[[1. 0.]] 3781 10390
[[1. 0.]] 7311 2705
[[1. 0.]] 7151 6821
[[1. 0.]] 5188 2817
[[1. 0.]] 8832 1553
[[1. 0.]] 2956 1880
[[1. 0.]] 14695 3982
[[1. 0.]] 3883 3890
[[1. 0.]] 7938 2512
[[1. 0.]] 3982 8832
[[1. 0.]] 6821 3781
[[1. 0.]] 2817 4146
[[1. 0.]] 2482 14695
[[1. 0.]] 10390 7151
[[1. 0.]] 1553 5188
[[1. 0.]] 3890 2956
[[1. 0.]] 1880 3883
[[1. 0.]] 2512 7311
[[1. 0.]] 2705 7938
[[1. 0.]] 14695 2817
[[1. 0.]] 8832 2482
[[1. 0.]] 3883 1553
[[1. 0.]] 5188 1880
[[1. 0.]] 3781 3890
[[1. 0.]] 2956 2705
[[1. 0.]] 7311 6821
[[1. 0.]] 7151 3982
[[1. 0.]] 7938 10390
[[1. 0.]] 4146 2512
[[1. 0.]] 3982 7938
[[1. 0.]] 1553 2956
[[1. 0.]] 3890 4146
[[1. 0.]] 1880 7311
[[1. 0.]] 2512 3883
[[1. 0.]] 2482 3781
[[1. 0.]] 10390 5188
[[1. 0.]] 2817 7151
[[1. 0.]] 6821 8832
[[1. 0.]] 6821 2512
[[1. 0.]] 1553 1880
[[1. 0.]] 8832 2956
[[1. 0.]] 3982 3781
[[1. 0.]] 3883 2817
[[1. 0.]] 4146 2705
[[1. 0.]] 2482 7938
[[1. 0.]] 7151 3890
[[1. 0.]] 5188 14695
[[1. 0.]] 73

[[1. 0.]] 5396 100
[[1. 0.]] 4257 8949
[[1. 0.]] 3861 7427
[[1. 0.]] 100 9319
[[1. 0.]] 2679 100
[[1. 0.]] 3100 4490
[[1. 0.]] 6735 1932
[[1. 0.]] 2588 6846
[[1. 0.]] 2866 1140
[[1. 0.]] 3817 3086
[[1. 0.]] 2280 100
[[1. 0.]] 2242 7928
[[1. 0.]] 9035 1781
[[1. 0.]] 100 2242
[[1. 0.]] 4490 1140
[[1. 0.]] 9319 100
[[1. 0.]] 6846 6735
[[1. 0.]] 3100 100
[[1. 0.]] 7928 3817
[[1. 0.]] 2866 9035
[[1. 0.]] 1932 2679
[[1. 0.]] 3086 2588
[[1. 0.]] 1781 2280
[[1. 0.]] 2679 9319
[[1. 0.]] 100 2588
[[1. 0.]] 9035 3100
[[1. 0.]] 1932 7928
[[1. 0.]] 100 2866
[[1. 0.]] 1140 100
[[1. 0.]] 2242 6846
[[1. 0.]] 6735 3086
[[1. 0.]] 2280 4490
[[1. 0.]] 3817 1781
[[1. 0.]] 2866 1932
[[1. 0.]] 3100 1140
[[1. 0.]] 9319 2280
[[1. 0.]] 4490 9035
[[1. 0.]] 3086 2242
[[1. 0.]] 2588 3817
[[1. 0.]] 100 6735
[[1. 0.]] 1781 100
[[1. 0.]] 7928 2679
[[1. 0.]] 6846 100
[[1. 0.]] 2280 3100
[[1. 0.]] 1140 9319
[[1. 0.]] 6735 7928
[[1. 0.]] 100 2866
[[1. 0.]] 9035 6846
[[1. 0.]] 2679 2588
[[1. 0.]] 100 3086
[[1. 0.]] 1932 

[[1. 0.]] 14695 100
[[1. 0.]] 2929 100
[[1. 0.]] 13105 7276
[[1. 0.]] 3612 9035
[[1. 0.]] 9221 6562
[[1. 0.]] 4207 8164
[[1. 0.]] 100 2929
[[1. 0.]] 100 14695
[[1. 0.]] 7276 3612
[[1. 0.]] 9035 13105
[[1. 0.]] 6154 9221
[[1. 0.]] 6562 6351
[[1. 0.]] 8832 4207
[[1. 0.]] 8164 9770
[[1. 0.]] 100 7928
[[1. 0.]] 2478 10390
[[1. 0.]] 9495 3647
[[1. 0.]] 8036 8949
[[1. 0.]] 10885 6821
[[1. 0.]] 6497 100
[[1. 0.]] 8083 9319
[[1. 0.]] 9329 100
[[1. 0.]] 7276 9495
[[1. 0.]] 9329 14695
[[1. 0.]] 7928 9770
[[1. 0.]] 6821 9221
[[1. 0.]] 8832 10885
[[1. 0.]] 100 13105
[[1. 0.]] 8949 10390
[[1. 0.]] 6154 9319
[[1. 0.]] 9770 7928
[[1. 0.]] 9221 6821
[[1. 0.]] 9495 7276
[[1. 0.]] 14695 9329


In [141]:
predictions1[0][0]

1.0

In [165]:
res_csv = {'date':train_csv.date,'id_HomeTeam':train_csv.idHomeTeam,'id_AwayTeam':train_csv.idAwayTeam,'homeTeam':train_csv.homeTeam,'AwayTeam':train_csv.awayTeam,'goalHomeTeam_HalfTime':predictions1[0][0],'goalAwayTeam_HalfTime':predictions1[0][1]}

In [166]:
df = pd.DataFrame(res_csv)
df

date  id_HomeTeam  id_AwayTeam                homeTeam  \
0     2019-08-09          548          523            AS Monaco FC   
1     2019-08-10          516          547  Olympique de Marseille   
2     2019-08-10          518          529         Montpellier HSC   
3     2019-08-10          522          530                OGC Nice   
4     2019-08-10          512          511       Stade Brestois 29   
...          ...          ...          ...                     ...   
1286  2020-02-26          523          109      Olympique Lyonnais   
1287  2020-03-10           95          102             Valencia CF   
1288  2020-03-10          721           73              RB Leipzig   
1289  2020-03-11          524            4  Paris Saint-Germain FC   
1290  2020-03-11           64           78            Liverpool FC   

                     AwayTeam  goalHomeTeam_HalfTime  goalAwayTeam_HalfTime  
0          Olympique Lyonnais                    1.0                    0.0  
1              Stade de Reims                    1.0                    0.0  
2       Stade Rennais FC 1901                    1.0                    0.0  
3                   Amiens SC                    1.0                    0.0  
4                 Toulouse FC                    1.0                    0.0  
...                       ...                    ...                    ...  
1286              Juventus FC                    1.0                    0.0  
1287              Atalanta BC                    1.0                    0.0  
1288     Tottenham Hotspur FC                    1.0                    0.0  
1289  BV Borussia 09 Dortmund                    1.0                    0.0  
1290  Club Atlético de Madrid                    1.0                    0.0  

[1291 rows x 7 columns]

In [ ]:
# X = train_csv.drop(['idHomeTeam','idAwayTeam','score','homeTeam','awayTeam','date','goalHomeTeam_HalfTime','goalAwayTeam_HalfTime','goalHomeTeam_FullTime','goalAwayTeam_FullTime'],axis=1).values
# X = X[:,1:]
# Y = train_csv.drop(['idHomeTeam','idAwayTeam','score','homeTeam','awayTeam','date','goalHomeTeam_FullTime','goalAwayTeam_FullTime','win_cons_home','win_cons_away','lose_cons_home','lose_cons_away','puissance_homeTeam','puissance_awayTeam'],axis=1).values
# Y = Y[:,1:]